"""Módulo de integração com Google Gemini.

Gerencia o prompt de sistema especializado (SRE Senior) e a geração
de respostas via streaming assíncrono.
"""

import logging
from collections.abc import AsyncGenerator

from google import genai
from google.genai import types

from src.core.config import Settings
from src.models.schemas import Chunk

logger = logging.getLogger(__name__)

GEMINI_MODEL = "gemini-2.5-flash"

SYSTEM_PROMPT = (
    "Você é um Engenheiro de SRE Senior especializado em análise de logs "
    "de aplicações e infraestrutura. Sua função é ajudar desenvolvedores a "
    "diagnosticar falhas, identificar causas raiz e sugerir correções com "
    "base nos logs fornecidos como contexto.\n\n"
    "## Formatação (OBRIGATÓRIO)\n"
    "Sempre responda usando Markdown bem estruturado:\n"
    "- Use títulos ### (nível 3) para separar seções. NUNCA use # ou ##.\n"
    "- Use **negrito** para destacar informações críticas.\n"
    "- Use listas (- ou 1.) para enumerar erros, causas ou recomendações.\n"
    "- Coloque nomes de classes, métodos e exceções em `código inline`.\n"
    "- Coloque trechos de log SEMPRE dentro de blocos de código com "
    "tripla crase (```). Nunca cole logs como texto corrido.\n"
    "- Cada bloco de código DEVE ter abertura e fechamento com ```.\n"
    "- Separe cada seção com uma linha em branco.\n"
    "- NÃO misture texto corrido com trechos de log na mesma linha.\n\n"
    "## Estrutura da Resposta\n"
    "Organize respostas longas nas seguintes seções:\n"
    "### Resumo\n"
    "Breve descrição do que foi encontrado (2-3 frases).\n"
    "### Erros Encontrados\n"
    "Lista dos erros com trechos de log em blocos de código.\n"
    "### Causa Raiz\n"
    "Análise da causa com evidências dos logs.\n"
    "### Recomendações\n"
    "Ações sugeridas em lista numerada.\n\n"
    "## Regras\n"
    "1. Baseie suas respostas EXCLUSIVAMENTE nos logs fornecidos.\n"
    "2. Se não houver informações suficientes, informe explicitamente.\n"
    "3. NÃO especule nem invente informações.\n"
    "4. Seja direto e objetivo."
)


def build_prompt(question: str, context_chunks: list[Chunk]) -> str:
    """Assemble the user prompt with context chunks and question.

    Args:
        question: The user's natural-language question.
        context_chunks: Relevant log chunks retrieved from ChromaDB.

    Returns:
        Formatted prompt string containing context and question.
    """
    context_parts: list[str] = []
    for i, chunk in enumerate(context_chunks, start=1):
        meta = chunk.metadata
        header = f"[Chunk {i} | {meta.filename} | {meta.log_level.value}"
        if meta.timestamp:
            header += f" | {meta.timestamp}"
        header += "]"
        context_parts.append(f"{header}\n{chunk.text}")

    context_block = (
        "\n\n".join(context_parts) if context_parts else "(Nenhum log disponível)"
    )

    return (
        f"## Contexto dos Logs\n\n{context_block}\n\n"
        f"## Pergunta do Usuário\n\n{question}"
    )


class LLMService:
    """Integration with Google Gemini for RAG response generation."""

    def __init__(self, settings: Settings) -> None:
        self._client = genai.Client(api_key=settings.GOOGLE_API_KEY)

    async def generate_stream(
        self,
        question: str,
        context_chunks: list[Chunk],
    ) -> AsyncGenerator[str, None]:
        """Generate a streaming response from Gemini.

        Args:
            question: User question in natural language.
            context_chunks: Relevant log chunks for context.

        Yields:
            Text tokens as they are generated by the model.
        """
        prompt = build_prompt(question, context_chunks)

        try:
            response = self._client.models.generate_content_stream(
                model=GEMINI_MODEL,
                contents=prompt,
                config=types.GenerateContentConfig(
                    system_instruction=SYSTEM_PROMPT,
                ),
            )
            for chunk in response:
                if chunk.text:
                    yield chunk.text
        except Exception as exc:
            logger.error("Gemini API error: %s", exc)
            yield f"Erro ao comunicar com o serviço de IA: {exc}"
