"""Módulo de integração com Google Gemini 1.5 Pro.

Gerencia o prompt de sistema especializado (SRE Senior) e a geração
de respostas via streaming assíncrono.
"""

import logging
from collections.abc import AsyncGenerator

import google.generativeai as genai

from backend.src.core.config import Settings
from backend.src.models.schemas import Chunk

logger = logging.getLogger(__name__)

GEMINI_MODEL = "gemini-1.5-pro"

SYSTEM_PROMPT = (
    "Você é um Engenheiro de SRE Senior especializado em análise de logs "
    "de aplicações e infraestrutura. Sua função é ajudar desenvolvedores a "
    "diagnosticar falhas, identificar causas raiz e sugerir correções com "
    "base nos logs fornecidos como contexto.\n\n"
    "Regras:\n"
    "1. Baseie suas respostas EXCLUSIVAMENTE nos logs fornecidos como contexto.\n"
    "2. Se não houver informações suficientes nos logs para responder, "
    "informe explicitamente que não encontrou dados suficientes. "
    "NÃO especule nem invente informações.\n"
    "3. Formate códigos de erro, comandos e trechos de log em blocos de "
    "código Markdown (```), facilitando a leitura.\n"
    "4. Quando identificar a causa raiz, destaque o trecho exato do log "
    "que evidencia o problema.\n"
    "5. Utilize linguagem técnica porém acessível, explicando termos "
    "complexos quando necessário.\n"
    "6. Para resumos executivos, seja direto e objetivo em no máximo 5 frases."
)


def build_prompt(question: str, context_chunks: list[Chunk]) -> str:
    """Assemble the user prompt with context chunks and question.

    Args:
        question: The user's natural-language question.
        context_chunks: Relevant log chunks retrieved from ChromaDB.

    Returns:
        Formatted prompt string containing context and question.
    """
    context_parts: list[str] = []
    for i, chunk in enumerate(context_chunks, start=1):
        meta = chunk.metadata
        header = f"[Chunk {i} | {meta.filename} | {meta.log_level.value}"
        if meta.timestamp:
            header += f" | {meta.timestamp}"
        header += "]"
        context_parts.append(f"{header}\n{chunk.text}")

    context_block = (
        "\n\n".join(context_parts) if context_parts else "(Nenhum log disponível)"
    )

    return (
        f"## Contexto dos Logs\n\n{context_block}\n\n"
        f"## Pergunta do Usuário\n\n{question}"
    )


class LLMService:
    """Integration with Google Gemini 1.5 Pro for RAG response generation."""

    def __init__(self, settings: Settings) -> None:
        genai.configure(api_key=settings.GOOGLE_API_KEY)
        self._model = genai.GenerativeModel(
            model_name=GEMINI_MODEL,
            system_instruction=SYSTEM_PROMPT,
        )

    async def generate_stream(
        self,
        question: str,
        context_chunks: list[Chunk],
    ) -> AsyncGenerator[str, None]:
        """Generate a streaming response from Gemini.

        Args:
            question: User question in natural language.
            context_chunks: Relevant log chunks for context.

        Yields:
            Text tokens as they are generated by the model.
        """
        prompt = build_prompt(question, context_chunks)

        try:
            response = self._model.generate_content(
                prompt,
                stream=True,
            )
            for chunk in response:
                if chunk.text:
                    yield chunk.text
        except Exception as exc:
            logger.error("Gemini API error: %s", exc)
            yield f"Erro ao comunicar com o serviço de IA: {exc}"
